file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}/output")
execute_process(
    COMMAND "${EXTRACTOR}" -2 -s -t 1 -y "${WORK}/output" -i "${ISO}"
    WORKING_DIRECTORY "${WORK}"
    RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Selected-track extraction failed: ${result}")
endif()
file(GLOB_RECURSE dsf_files "${WORK}/output/*.dsf")
file(GLOB_RECURSE partial_files "${WORK}/output/*.partial.dsf")
file(GLOB_RECURSE inprogress_files "${WORK}/output/*.inprogress.dsf")
file(GLOB_RECURSE log_files "${WORK}/output/*.log")
list(LENGTH dsf_files dsf_count)
list(LENGTH partial_files partial_count)
list(LENGTH inprogress_files inprogress_count)
list(LENGTH log_files log_count)
if(NOT dsf_count EQUAL 1 OR NOT partial_count EQUAL 0 OR NOT inprogress_count EQUAL 0)
    message(FATAL_ERROR "Expected exactly one clean DSF output")
endif()
if(log_count LESS 1)
    message(FATAL_ERROR "Expected an automatic session log")
endif()
list(GET log_files 0 log_file)
file(READ "${log_file}" log_content)
if(NOT log_content MATCHES "session summary result=clean exit_status=0")
    message(FATAL_ERROR "Session log did not record a clean result")
endif()
if(NOT log_content MATCHES "output=dsf area=stereo channels=2 encoding=(DSD|DST) destination=")
    message(FATAL_ERROR "Session log did not record the selected format and area")
endif()
